post:
  summary: 更改实例配置
  parameters: 
    - $ref: '../parameters/instance.yaml#/instanceId'
    - in: body
      name: server
      required: true
      schema:
        $ref: '../schemas/instance.yaml#/InstanceChangeConfig' 
  responses:
    200:
      description: 实例信息
      schema:
        $ref: '../schemas/instance.yaml#/InstanceResponse'
  tags:
    - instance