ServiceListResponse:
  type: object
  properties:
    limit:
      type: integer
      example: 20
    offset:
      type: integer
      example: 0
    total:
      type: integer
      description: 总量
    services:
      type: array
      items:
        $ref: "#/Service"

ServiceGetResponse:
  type: object
  properties:
    service:
      type: object
      $ref: "#/Service"

ServicePutRequestInput:
  type: object
  properties:
    name:
      type: string
      description: 服务的名称
      example: keystone, region, glance, ...
    type:
      type: string
      description: 服务的类型
      example: identity, compute, image, ...
    description:  
      type: string
      description: 服务的描述
    enabled:
      type: boolean
      description: 是否启用／禁用服务

ServiceCreateInput:
  type: object
  properties:
    name:
      type: string
      description: 服务的名称，全局唯一
      example: keystone
    type:
      type: string
      description: 服务的类型
      example: identity
    enabled:
      type: boolean
      description: 服务是否启用／禁用
      default: true
    description:
      type: string
      description: 服务的描述

Service:
  type: object
  description: 服务
  properties:
    id:
      type: string
      description: 服务ID
      readOnly: true
    name:
      type: string
      description: 服务名，全局唯一
    type:
      type: string
      description: 服务类型
    enabled:
      type: boolean
      description: 服务是否启用／禁用
    can_delete:
      type: boolean
      description: 是否可以删除
    description:
      type: string
      description: 服务的描述信息
