get:
  summary: 获得指定项目的详情
  parameters:
    - $ref: '../parameters/project.yaml#/project_id'
  responses:
    200:
      description: 项目信息
      schema:
        $ref: "../schemas/project.yaml#/ProjectGetResponse"
  tags:
    - projects

put:
  summary: 更新指定项目的属性
  parameters:
    - $ref: '../parameters/project.yaml#/project_id'
    - name: project
      in: body
      required: true
      schema:
        $ref: "../schemas/project.yaml#/ProjectPutRequestInput"
  responses:
    200:
      description: 项目信息
      schema:
        $ref: "../schemas/project.yaml#/ProjectGetResponse"
  tags:
    - projects

delete:
  summary: 删除指定项目
  parameters:
    - $ref: '../parameters/project.yaml#/project_id'
  responses:
    200:
      description: 被删除的项目信息
      schema:
        $ref: "../schemas/project.yaml#/ProjectGetResponse"
  tags:
    - projects
