get:
  summary: 按指定条件列出服务
  parameters:
    - $ref: '../parameters/common.yaml#/offset'
    - $ref: '../parameters/common.yaml#/limit'
    - $ref: '../parameters/common.yaml#/search'
  responses:
    200:
      description: 服务列表信息
      schema:
        $ref: "../schemas/service.yaml#/ServiceListResponse"
  tags:
    - services

post:
  summary: 新建一个服务
  parameters:
    - name: service
      in: body
      required: true
      schema:
        $ref: "../schemas/service.yaml#/ServiceCreateInput"
  responses:
    200:
      description: 服务信息
      schema:
        $ref: "../schemas/service.yaml#/ServiceGetResponse"
  tags:
    - services
