get:
  summary: 获得指定服务的详情
  parameters:
    - $ref: '../parameters/service.yaml#/service_id'
  responses:
    200:
      description: 服务信息
      schema:
        $ref: "../schemas/service.yaml#/ServiceGetResponse"
  tags:
    - services

put:
  summary: 更新指定服务的属性
  parameters:
    - $ref: '../parameters/service.yaml#/service_id'
    - name: service
      in: body
      required: true
      schema:
        $ref: "../schemas/service.yaml#/ServicePutRequestInput"
  responses:
    200:
      description: 服务信息
      schema:
        $ref: "../schemas/service.yaml#/ServiceGetResponse"
  tags:
    - services

delete:
  summary: 删除指定服务
  parameters:
    - $ref: '../parameters/service.yaml#/service_id'
  responses:
    200:
      description: 被删除的服务信息
      schema:
        $ref: "../schemas/service.yaml#/ServiceGetResponse"
  tags:
    - services
